apiVersion: v1
kind: Service
metadata:
  name: mypyapp-service
  namespace: pyapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      
  selector:
    app: mypyapp
